<h1 style="text-align:center; 
           background:rgb(139, 217, 144); 
           color: rgb(4, 82, 9);
           font-size:45px; 
           padding:20px;
           border-radius:12px;">
     <b> Future Stock Prediction(ML)</b>
</h1>

### <b>🧑‍💼 Project Author</b>

***Author: Muhammad Usman***

***Artificial Intelligence/Machine Learning/DataEngineering Enthusiast***

***Date: MAY 2026***

<h2 style="text-align:center; 
           background: rgb(139, 217, 144);  
           color:rgb(4, 82, 9); 
           font-size:42px; 
           padding:12px;
           border-radius:12px;
           display: inline-block">
     <b>Preparing Data for Machine Learning</b>
</h2>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.offline as pyo

import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Load dataset with Date column
appl_ml = pd.read_csv(
    "aapl_preprocessed.csv",
    parse_dates=['Date'],
    index_col='Date'
)

# Sort dates
appl_ml = appl_ml.sort_index()

In [3]:
appl_ml.head()

,Close,High,Low,Open,Volume,Year,Month,Day,IsYearStart,IsYearEnd,Returns,Returns (%),MA20,MA50,Volatility,lag1,lag2
Date,,,,,,,,,,,,,,,,,
2010-03-16,6.725198,6.741079,6.667070,6.717108,446908000,2010,March,Tuesday,0,0,0.002725,0.272533,6.346270,6.201066,0.012642,6.706920,6.789618
2010-03-17,6.715309,6.785122,6.689840,6.738680,450956800,2010,March,Wednesday,0,0,-0.001471,-0.147053,6.378585,6.207124,0.012552,6.725198,6.706920
2010-03-18,6.731189,6.741676,6.670064,6.714708,342109600,2010,March,Thursday,0,0,0.002365,0.236476,6.411125,6.213279,0.012546,6.715309,6.725198
2010-03-19,6.659277,6.748866,6.628714,6.735383,559445600,2010,March,Friday,0,0,-0.010683,-1.068337,6.441957,6.220038,0.012797,6.731189,6.715309
2010-03-22,6.734185,6.771639,6.596355,6.605944,456419600,2010,March,Monday,0,0,0.011249,1.124871,6.478406,6.228530,0.012590,6.659277,6.731189

In [5]:
features = ['Open', 'High', 'Low', 'Volume', 'MA20', 'MA50', 'Volatility', 'lag1', 'lag2']
target = 'Close'

X = appl_ml[features]
y = appl_ml[target]

In [6]:
split = int(len(appl_ml) * 0.8)

X_train = X[:split]
X_test = X[split:]

y_train = y[:split]
y_test = y[split:]

### **Observation**
---
- Data is split chronologically (not randomly) to preserve time order.
- This mimics real-world forecasting conditions.

<h2 style="text-align:center; 
           background: rgb(139, 217, 144);  
           color:rgb(4, 82, 9); 
           font-size:42px; 
           padding:12px;
           border-radius:12px;
           display: inline-block">
     <b>Model Training</b>
</h2>

In [7]:
appl_ml.isnull().sum()

Close          0
High           0
Low            0
Open           0
Volume         0
Year           0
Month          0
Day            0
IsYearStart    0
IsYearEnd      0
Returns        0
Returns (%)    0
MA20           0
MA50           0
Volatility     0
lag1           0
lag2           0
dtype: int64

In [8]:
from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

lr_preds = lr_model.predict(X_test)

In [9]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

rf_preds = rf_model.predict(X_test)

**Evaluation**

In [57]:
def evaluate(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    
    return mae, rmse

# Linear Regression
lr_mae, lr_rmse = evaluate(y_test, lr_preds)
print(f"Linear Regression - MAE: {lr_mae:.2f}, RMSE: {lr_rmse:.2f}")

# Random Forest
rf_mae, rf_rmse = evaluate(y_test, rf_preds)
print(f"Random Forest - MAE: {rf_mae:.2f}, RMSE: {rf_rmse:.2f}")

Linear Regression - MAE: 0.91, RMSE: 1.24
Random Forest - MAE: 38.13, RMSE: 50.46

### **Observations**
---
The stock features had strong linear relationships with the target closing price. 

Linear Regression captured these relationships effectively, while Random Forest struggled with sequential time-series behavior and produced higher prediction errors

In [41]:
fig = go.Figure()

# Actual values
fig.add_trace(go.Scatter(
    y=y_test.values,
    mode='lines',
    name='Actual Price'
))

# LR predictions
fig.add_trace(go.Scatter(
    y=lr_preds,
    mode='lines',
    name='Predicted Price (LR)'
))

fig.update_layout(
    title="Actual vs Predicted Prices",
    xaxis_title="Time",
    yaxis_title="Price"
)

fig.show()

<h2 style="text-align:center; 
           background: rgb(139, 217, 144);  
           color:rgb(4, 82, 9); 
           font-size:42px; 
           padding:12px;
           border-radius:12px;
           display: inline-block">
     <b>Predictions</b>
</h2>

### **Generating Future Predictions**

In [11]:
# Number of future days
future_days = 7

# Last known feature row
last_input = X.iloc[-1].values.reshape(1, -1)

future_predictions = []

# Predict future values iteratively
for i in range(future_days):

    # Predict next close price
    pred = lr_model.predict(last_input)[0]

    # Store prediction
    future_predictions.append(pred)

    # Update input with predicted value
    last_input = np.roll(last_input, -1)

    # Put prediction in last position
    last_input[0, -1] = pred

### **Fixing Date Issue**

In [12]:
# Generate next 7 business days
future_dates = pd.date_range(
    start=appl_ml.index[-1] + pd.offsets.BDay(1),
    periods=future_days,
    freq='B'
)

### **Prediction Table**

In [13]:
future_df = pd.DataFrame({
    "Date": future_dates,
    "Predicted_Close": future_predictions
})

# Add weekday names
future_df['Day'] = future_df['Date'].dt.day_name()

future_df

        Date  Predicted_Close        Day
0 2026-05-11     2.942447e+02     Monday
1 2026-05-12     4.264921e+07    Tuesday
2 2026-05-13     4.607574e+07  Wednesday
3 2026-05-14    -3.528107e+07   Thursday
4 2026-05-15    -3.238842e+07     Friday
5 2026-05-18    -2.426973e+07     Monday
6 2026-05-19     2.647157e+07    Tuesday

###  **OBSERVATIONS**
---
- The Linear Regression model performed well during evaluation on historical test data.
- However, during iterative future forecasting, the predicted values became unrealistic and unstable.
- Some predictions reached extremely large positive and negative values, which are not practically possible for stock prices.
- This issue occurs because Linear Regression does not naturally model sequential dependencies in time-series forecasting

### **Viz Through Graph**

In [14]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=future_df['Date'],
    y=future_df['Predicted_Close'],
    mode='lines+markers',
    name='Predicted Future Price',
    line=dict(color='green', width=3),
    marker=dict(size=8),
    hovertemplate=
        'Date: %{x}<br>' +
        'Predicted Close: %{y:.2f}<br>' +
        'Day: %{text}<extra></extra>',
    text=future_df['Day']
))

fig.update_layout(
    title="Future Stock Price Prediction (Next 7 Days)",
    xaxis_title="Date",
    yaxis_title="Predicted Close Price",
    hovermode="x"
)

fig.show()

<h2 style="text-align:center; 
           background: rgb(139, 217, 144);  
           color:rgb(4, 82, 9); 
           font-size:42px; 
           padding:12px;
           border-radius:12px;
           display: inline-block">
     <b>LSTM MODEL</b>
</h2>

---
#### ***🧠 Deep Learning Model: LSTM***

Traditional ML models cannot effectively remember `long-term sequential dependencies` in stock prices.

Therefore, `LSTM (Long Short-Term Memory)` was introduced for time-series forecasting.

### **Scaling Data**

In [15]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaled_close = scaler.fit_transform(
    appl_ml[['Close']]
)

In [16]:
scaler

MinMaxScaler()

### **Create Sequences**

In [17]:
X_lstm = []
y_lstm = []

window_size = 60

for i in range(window_size, len(scaled_close)):
    X_lstm.append(scaled_close[i-window_size:i])
    y_lstm.append(scaled_close[i])

X_lstm = np.array(X_lstm)
y_lstm = np.array(y_lstm)

## **Train-Test Split**

In [18]:
split = int(len(X_lstm) * 0.8)

X_train_lstm = X_lstm[:split]
X_test_lstm = X_lstm[split:]

y_train_lstm = y_lstm[:split]
y_test_lstm = y_lstm[split:]

### **Build LSTM Model**

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential()

model.add(LSTM(
    50,
    return_sequences=True,
    input_shape=(X_train_lstm.shape[1], 1)
))

model.add(Dropout(0.2))

model.add(LSTM(50))

model.add(Dropout(0.2))

model.add(Dense(1))

model.compile(
    optimizer='adam',
    loss='mean_squared_error'
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

## **Train Model**

In [21]:
history = model.fit(
    X_train_lstm,
    y_train_lstm,
    epochs=10,
    batch_size=32
)

Epoch 1/10
101/101 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - loss: 0.0021
Epoch 2/10
101/101 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - loss: 5.3206e-04
Epoch 3/10
101/101 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - loss: 6.2451e-04
Epoch 4/10
101/101 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - loss: 5.9843e-04
Epoch 5/10
101/101 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - loss: 4.4649e-04
Epoch 6/10
101/101 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - loss: 4.3263e-04
Epoch 7/10
101/101 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - loss: 4.5723e-04
Epoch 8/10
101/101 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - loss: 4.5317e-04
Epoch 9/10
101/101 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - loss: 4.2727e-04
Epoch 10/10
101/101 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - loss: 4.0958e-04

## **Predict**

In [42]:
lstm_preds = model.predict(X_test_lstm)

# Convert back to real prices
lstm_preds = scaler.inverse_transform(lstm_preds)


# Actual values
y_test_actual = scaler.inverse_transform(
    y_test_lstm.reshape(-1,1)
)

26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step

In [23]:
lstm_preds

array([[146.29007],
       [145.63503],
       [145.00668],
       [144.74474],
       [144.90532],
       [145.19722],
       [145.6326 ],
       [145.991  ],
       [146.14828],
       [146.28067],
       [146.51247],
       [146.81737],
       [147.3229 ],
       [147.87311],
       [148.56134],
       [149.40424],
       [150.2031 ],
       [150.98674],
       [151.78531],
       [152.4206 ],
       [152.8711 ],
       [153.35913],
       [153.93323],
       [154.6794 ],
       [155.56416],
       [156.44778],
       [157.15942],
       [157.76625],
       [158.10432],
       [158.17409],
       [158.02419],
       [158.07213],
       [158.22255],
       [158.43568],
       [158.75125],
       [159.18115],
       [159.59679],
       [159.87784],
       [160.07144],
       [160.10019],
       [160.02103],
       [160.15704],
       [160.49754],
       [160.94461],
       [161.36858],
       [161.68347],
       [161.80602],
       [162.26372],
       [162.89706],
       [163.50143],
       [164.1554 ],
       [164.80573],
       [165.35286],
       [165.76663],
       [166.06618],
       [166.30907],
       [166.64151],
       [167.01561],
       [167.33572],
       [167.44188],
       [167.4215 ],
       [167.38881],
       [167.49724],
       [167.80197],
       [168.21065],
       [168.83105],
       [169.59512],
       [170.31717],
       [170.94112],
       [171.37398],
       [171.81992],
       [172.26447],
       [172.84996],
       [173.45644],
       [174.07614],
       [174.78561],
       [175.43735],
       [176.01472],
       [176.44106],
       [176.92502],
       [177.39095],
       [177.73131],
       [178.13763],
       [178.62749],
       [179.15898],
       [179.94534],
       [180.74718],
       [181.4395 ],
       [182.0428 ],
       [182.47778],
       [182.65157],
       [182.616  ],
       [182.5505 ],
       [182.51613],
       [182.5152 ],
       [182.7363 ],
       [183.06712],
       [183.53055],
       [183.92728],
       [184.18427],
       [184.38199],
       [184.57828],
       [184.81258],
       [184.97845],
       [185.24828],
       [185.60056],
       [185.93196],
       [186.04657],
       [185.9321 ],
       [185.1265 ],
       [183.7536 ],
       [182.16718],
       [180.45398],
       [178.76828],
       [177.2213 ],
       [175.97139],
       [174.8764 ],
       [173.90536],
       [172.92389],
       [172.03142],
       [171.33409],
       [170.8907 ],
       [170.87343],
       [170.84251],
       [170.94293],
       [171.20952],
       [171.79881],
       [172.76442],
       [173.91731],
       [175.2073 ],
       [176.50792],
       [177.31474],
       [177.43036],
       [177.13164],
       [176.65501],
       [175.914  ],
       [174.93507],
       [173.96587],
       [173.02513],
       [172.34877],
       [171.95389],
       [171.55304],
       [171.08485],
       [170.65486],
       [170.35301],
       [169.90431],
       [169.30249],
       [168.65688],
       [168.05626],
       [167.67813],
       [167.38654],
       [167.24886],
       [167.29303],
       [167.60548],
       [168.1577 ],
       [168.78954],
       [169.51404],
       [170.30038],
       [170.95888],
       [171.48276],
       [171.7879 ],
       [171.85327],
       [171.73775],
       [171.35887],
       [170.84706],
       [170.31142],
       [169.65736],
       [168.72177],
       [167.75172],
       [166.94737],
       [166.33322],
       [166.07811],
       [166.28723],
       [166.72482],
       [167.4364 ],
       [168.42743],
       [169.5918 ],
       [170.75713],
       [172.09695],
       [173.3551 ],
       [174.63559],
       [175.87343],
       [177.1018 ],
       [178.23769],
       [179.34364],
       [180.30473],
       [181.14964],
       [181.78125],
       [182.22453],
       [182.55435],
       [182.72769],
       [182.8271 ],
       [182.95094],
       [182.97375],
       [183.17476],
       [183.40645],
       [183.76344],
       [184.26115],
       [184.66196],
       [185.06825],
       [185.6425 ],
       [186.29094],
       [186.91135],
       [187.37038],
       [187.7587 ],
       [187.94553],
       [187.98442],
       [187.86069],
       [187.61028],
       [187.30336],
       [187.0083 ],
       [186.67896],
       [185.93776],
       [184.90733],
       [183.61908],
       [182.21164],
       [181.08855],
       [180.19637],
       [179.58122],
       [179.14957],
       [178.88538],
       [178.60641],
       [178.27966],
       [178.30064],
       [178.71251],
       [179.48741],
       [180.5187 ],
       [181.60074],
       [182.61946],
       [183.41884],
       [183.98009],
       [184.12616],
       [183.77992],
       [183.29292],
       [182.68561],
       [182.1582 ],
       [181.81665],
       [181.62625],
       [181.48264],
       [181.42673],
       [181.32639],
       [181.07816],
       [180.69853],
       [180.24197],
       [179.67331],
       [179.02795],
       [178.42375],
       [178.01047],
       [177.63556],
       [177.23201],
       [176.92633],
       [176.6284 ],
       [176.3164 ],
       [175.95024],
       [175.29866],
       [174.21007],
       [172.85558],
       [171.41278],
       [170.11578],
       [169.12283],
       [168.42308],
       [167.83441],
       [167.47128],
       [167.25072],
       [167.20227],
       [167.40744],
       [167.91534],
       [168.13998],
       [168.22623],
       [168.1243 ],
       [167.83876],
       [167.67195],
       [167.4798 ],
       [167.20108],
       [166.81467],
       [166.43423],
       [166.03223],
       [165.69084],
       [165.34282],
       [165.08913],
       [164.79776],
       [164.9421 ],
       [165.44289],
       [165.9086 ],
       [166.12239],
       [166.07388],
       [165.79851],
       [165.2714 ],
       [164.66998],
       [164.12514],
       [163.7832 ],
       [163.64882],
       [163.62346],
       [163.92479],
       [164.22104],
       [164.43439],
       [164.80272],
       [165.86678],
       [167.20099],
       [168.66599],
       [170.13286],
       [171.60829],
       [172.90764],
       [174.2007 ],
       [175.46712],
       [176.7692 ],
       [178.01195],
       [179.13509],
       [180.17604],
       [181.17178],
       [181.98286],
       [182.3801 ],
       [182.67654],
       [182.88501],
       [183.0445 ],
       [183.22453],
       [183.46477],
       [183.83589],
       [184.28476],
       [184.8457 ],
       [185.3547 ],
       [185.94283],
       [186.30981],
       [187.3618 ],
       [189.12132],
       [191.28435],
       [193.4512 ],
       [195.72122],
       [197.74547],
       [199.19476],
       [200.04688],
       [200.49805],
       [200.71782],
       [201.02933],
       [201.42857],
       [201.6518 ],
       [202.12462],
       [202.92738],
       [203.96124],
       [205.35951],
       [206.975  ],
       [208.6662 ],
       [210.54294],
       [212.07248],
       [213.46022],
       [214.88373],
       [216.24998],
       [217.12915],
       [217.36572],
       [217.19113],
       [216.74542],
       [216.22537],
       [215.30814],
       [214.15454],
       [212.96051],
       [211.84155],
       [210.88425],
       [210.29509],
       [209.7544 ],
       [209.3801 ],
       [208.49583],
       [207.24045],
       [205.98727],
       [205.02605],
       [204.49142],
       [204.35843],
       [204.71626],
       [205.38405],
       [206.38237],
       [207.59448],
       [208.84412],
       [210.06471],
       [211.17043],
       [212.0109 ],
       [212.76419],
       [213.42487],
       [214.03265],
       [214.47173],
       [214.9753 ],
       [215.43219],
       [215.45673],
       [215.09999],
       [214.61829],
       [213.99435],
       [213.33449],
       [212.65125],
       [212.1574 ],
       [211.82228],
       [211.59752],
       [211.08777],
       [210.46918],
       [210.054  ],
       [210.28296],
       [210.85638],
       [211.51076],
       [212.22601],
       [212.86447],
       [213.47762],
       [214.04369],
       [214.85243],
       [215.34221],
       [215.6425 ],
       [215.73018],
       [215.74626],
       [215.40709],
       [215.12143],
       [215.10857],
       [215.2377 ],
       [215.36319],
       [215.7057 ],
       [216.3079 ],
       [216.90573],
       [217.4849 ],
       [218.17969],
       [218.98206],
       [219.7573 ],
       [220.15572],
       [220.28314],
       [220.27725],
       [220.30531],
       [220.3678 ],
       [220.23601],
       [219.74623],
       [218.88931],
       [217.80849],
       [216.74837],
       [215.73056],
       [215.10107],
       [214.74013],
       [214.41507],
       [214.13968],
       [213.96565],
       [214.05157],
       [214.09741],
       [214.30194],
       [214.60115],
       [214.98264],
       [215.35893],
       [215.78677],
       [216.39449],
       [217.20064],
       [218.0659 ],
       [219.0528 ],
       [220.17805],
       [221.49184],
       [222.84898],
       [224.1392 ],
       [225.28252],
       [226.48558],
       [227.69469],
       [228.74533],
       [229.71252],
       [230.56535],
       [231.46039],
       [232.46011],
       [233.12766],
       [233.6545 ],
       [234.33038],
       [235.09128],
       [236.02911],
       [237.05663],
       [237.86252],
       [238.27524],
       [238.30847],
       [237.70844],
       [236.73546],
       [235.69336],
       [234.51347],
       [233.36952],
       [231.97952],
       [230.39911],
       [228.74504],
       [227.43709],
       [225.85585],
       [224.33728],
       [222.51593],
       [220.7147 ],
       [219.0354 ],
       [217.49854],
       [216.58688],
       [216.62889],
       [217.33054],
       [218.29709],
       [219.26761],
       [219.6873 ],
       [220.02257],
       [220.2445 ],
       [220.42531],
       [220.23056],
       [219.83826],
       [219.64444],
       [219.83856],
       [220.54291],
       [221.70201],
       [223.05704],
       [224.46417],
       [225.85814],
       [227.12314],
       [228.30821],
       [229.35051],
       [229.82787],
       [229.74294],
       [229.58386],
       [229.15166],
       [228.46376],
       [227.65651],
       [226.80759],
       [226.21959],
       [225.13736],
       [223.44351],
       [221.25455],
       [218.46744],
       [215.73535],
       [213.24966],
       [211.01852],
       [209.2634 ],
       [207.86118],
       [207.0353 ],
       [206.77408],
       [207.06908],
       [207.55762],
       [208.27545],
       [208.72044],
       [209.22075],
       [209.77225],
       [210.3582 ],
       [209.67412],
       [207.36595],
       [203.77689],
       [199.07338],
       [195.58786],
       [192.57349],
       [190.5697 ],
       [189.60812],
       [189.3572 ],
       [189.1024 ],
       [189.02843],
       [188.8286 ],
       [188.95883],
       [189.57211],
       [190.67612],
       [192.06984],
       [193.6027 ],
       [195.17868],
       [196.74599],
       [198.24414],
       [199.1089 ],
       [199.12755],
       [198.58615],
       [197.58601],
       [196.4431 ],
       [195.35272],
       [195.13333],
       [195.60555],
       [196.4584 ],
       [197.44434],
       [198.43265],
       [199.19868],
       [199.65245],
       [199.5852 ],
       [199.15016],
       [198.14052],
       [197.14244],
       [196.22635],
       [195.40317],
       [194.75494],
       [194.31525],
       [194.13435],
       [194.10254],
       [194.0359 ],
       [194.1517 ],
       [194.21948],
       [194.32889],
       [194.21783],
       [194.00316],
       [193.56726],
       [193.14264],
       [192.58275],
       [192.03708],
       [191.80435],
       [191.81433],
       [191.90877],
       [192.12868],
       [192.37636],
       [192.6292 ],
       [193.11401],
       [193.86842],
       [195.02142],
       [196.41187],
       [197.63896],
       [198.68279],
       [199.60101],
       [200.44899],
       [201.1163 ],
       [201.47124],
       [201.63577],
       [201.73022],
       [201.76549],
       [201.83371],
       [201.99727],
       [202.32692],
       [202.72357],
       [203.11363],
       [203.47977],
       [203.81445],
       [203.93695],
       [203.78506],
       [203.38092],
       [202.53113],
       [201.52231],
       [200.45316],
       [200.04744],
       [200.49226],
       [202.0121 ],
       [203.9892 ],
       [206.27303],
       [208.80432],
       [211.27052],
       [213.44595],
       [215.23781],
       [216.63737],
       [217.41385],
       [217.68153],
       [217.7824 ],
       [217.73216],
       [217.72636],
       [217.82098],
       [218.1001 ],
       [218.45103],
       [218.67978],
       [219.34662],
       [220.3074 ],
       [221.38374],
       [222.34874],
       [222.96342],
       [222.85995],
       [222.5142 ],
       [222.27312],
       [222.2703 ],
       [222.5075 ],
       [222.93257],
       [223.38028],
       [224.27164],
       [226.00282],
       [228.02849],
       [229.9754 ],
       [232.0073 ],
       [233.849  ],
       [235.37854],
       [236.61328],
       [237.62126],
       [238.51404],
       [239.3224 ],
       [239.9413 ],
       [240.38927],
       [240.79352],
       [240.8986 ],
       [240.29254],
       [239.44237],
       [238.49646],
       [237.65456],
       [236.82506],
       [236.36018],
       [236.74608],
       [237.65761],
       [238.58151],
       [239.52177],
       [240.59045],
       [242.01213],
       [243.55263],
       [245.10016],
       [246.63922],
       [247.99515],
       [249.06078],
       [249.9278 ],
       [250.6104 ],
       [251.10689],
       [251.37546],
       [251.5588 ],
       [252.02098],
       [252.508  ],
       [252.95343],
       [253.30974],
       [253.28975],
       [253.04478],
       [252.7404 ],
       [252.28073],
       [252.0769 ],
       [252.30112],
       [252.83496],
       [253.5605 ],
       [254.4303 ],
       [255.57643],
       [256.98553],
       [258.32886],
       [259.33258],
       [259.94144],
       [260.20682],
       [260.19617],
       [260.11075],
       [259.93768],
       [259.74222],
       [259.29987],
       [258.7764 ],
       [258.07242],
       [257.33472],
       [256.71588],
       [256.05313],
       [255.50175],
       [255.14236],
       [254.90242],
       [254.77814],
       [254.69347],
       [254.56802],
       [254.37682],
       [253.93478],
       [253.08221],
       [251.9208 ],
       [250.57336],
       [249.2276 ],
       [248.03181],
       [247.06389],
       [246.24382],
       [245.47444],
       [244.63457],
       [243.28499],
       [241.78358],
       [240.32674],
       [238.98134],
       [238.24614],
       [238.10585],
       [238.2405 ],
       [238.6542 ],
       [239.279  ],
       [240.61807],
       [242.25595],
       [244.38719],
       [246.62254],
       [248.89397],
       [250.82054],
       [252.33896],
       [253.59792],
       [253.77419],
       [252.9362 ],
       [252.01463],
       [251.11452],
       [250.07567],
       [249.2783 ],
       [248.77815],
       [248.85806],
       [249.41138],
       [250.1449 ],
       [250.41708],
       [250.42813],
       [250.20702],
       [249.78276],
       [249.1304 ],
       [248.21745],
       [247.35733],
       [246.64328],
       [246.07199],
       [245.33133],
       [244.21053],
       [243.10121],
       [242.15282],
       [241.11482],
       [240.04651],
       [238.97682],
       [238.19359],
       [237.64801],
       [237.35199],
       [237.24872],
       [237.02757],
       [236.62398],
       [236.5643 ],
       [236.81924],
       [237.272  ],
       [237.99431],
       [238.50616],
       [239.18333],
       [239.99605],
       [240.83339],
       [241.54973],
       [242.11806],
       [243.00731],
       [243.83675],
       [244.98886],
       [246.41423],
       [247.4939 ],
       [248.71288],
       [249.92667],
       [250.90964],
       [251.47594],
       [251.9313 ],
       [252.24315],
       [252.51694],
       [253.27087],
       [254.0566 ],
       [255.25761],
       [256.81232],
       [258.46674]], dtype=float32)

**lstm evaluation**

In [46]:
lstm_mae = mean_absolute_error(
    y_test_actual,
    lstm_preds
)

lstm_rmse = np.sqrt(
    mean_squared_error(
        y_test_actual,
        lstm_preds
    )
)

print("LSTM Performance")
print("MAE :", lstm_mae)
print("RMSE:", lstm_rmse)

LSTM Performance
MAE : 10.302370469073082
RMSE: 12.544117562659679

**Viz (LSTM vs Predicted values)**

In [47]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    y=y_test_actual.flatten(),
    mode='lines',
    name='Actual Price'
))

fig.add_trace(go.Scatter(
    y=lstm_preds.flatten(),
    mode='lines',
    name='Predicted Price (LSTM)'
))

fig.update_layout(
    title="LSTM Actual vs Predicted Prices",
    xaxis_title="Time",
    yaxis_title="Stock Price"
)

fig.show()

**Future forcasting using LSTM**

In [48]:
future_days = 7

last_sequence = scaled_close[-60:]

future_predictions = []

current_sequence = last_sequence.copy()

for _ in range(future_days):

    pred = model.predict(
        current_sequence.reshape(1,60,1),
        verbose=0
    )

    future_predictions.append(pred[0,0])

    current_sequence = np.append(
        current_sequence[1:],
        pred
    )

**converting future values**

In [49]:
future_predictions = scaler.inverse_transform(
    np.array(future_predictions).reshape(-1,1)
)

**future dates**

In [50]:
future_dates = pd.date_range(
    start=appl_ml.index[-1] + pd.offsets.BDay(1),
    periods=7,
    freq='B'
)

**final forcasting table**

In [51]:
future_df_lstm = pd.DataFrame({
    "Date": future_dates,
    "Predicted_Close": future_predictions.flatten()
})

future_df_lstm['Day'] = future_df_lstm['Date'].dt.day_name()

future_df_lstm

        Date  Predicted_Close        Day
0 2026-05-11       260.413513     Monday
1 2026-05-12       260.424652    Tuesday
2 2026-05-13       259.304657  Wednesday
3 2026-05-14       257.470215   Thursday
4 2026-05-15       255.211182     Friday
5 2026-05-18       252.720749     Monday
6 2026-05-19       250.124359    Tuesday

### **comparision evaluation table**

In [59]:
comparison_df = pd.DataFrame({

    "Model": [
        "Linear Regression",
        "Random Forest",
        "LSTM"
    ],

    "MAE": [
        lr_mae,
        rf_mae,
        lstm_mae
    ],

    "RMSE": [
        lr_rmse,
        rf_rmse,
        lstm_rmse
    ]
})

comparison_df

               Model        MAE       RMSE
0  Linear Regression   0.905245   1.243372
1      Random Forest  38.134439  50.457509
2               LSTM  10.302370  12.544118

### **Future Forecast Graph**

In [52]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=future_df_lstm['Date'],
    y=future_df_lstm['Predicted_Close'],
    mode='lines+markers',
    name='Future Forecast'
))

fig.update_layout(
    title="Next 7 Days Forecast using LSTM",
    xaxis_title="Date",
    yaxis_title="Predicted Price"
)

fig.show()

### **Observation**
---
- according to the above graph of 7 days forcast, the stock price is expected to remain same on 12th may, 2026 and then it will start to descrease in business days.

- Linear Regression achieved the best historical regression accuracy.
- Random Forest struggled with sequential market behavior.
- LSTM produced more stable future forecasting results.
- Deep learning models are more suitable for sequential stock forecasting tasks.

### **Exporting predicted values**

In [63]:
future_df_lstm.to_csv('future_predictions_lstm.csv', index=False)